inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

# 対象外
AllCops:
  Exclude:
    - "vendor/**/*"
    - "bin/**"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "lib/**/*"
  DisplayCopNames: true
  TargetRubyVersion: 2.6

# trueかfalseを設定しないと警告が出る
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

##################### Style ##################################

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

# ドキュメントの無いpublic classを許可する
Style/Documentation:
  Enabled: false

# !! のイディオムを許可
Style/DoubleNegation:
  Enabled: false

#文字列をfreezeするか
Style/FrozenStringLiteralComment:
  Enabled: false

# selfが無くても良い時に省略するか。model内において、ローカル変数とメソッド呼び出しの区別をつけた方が分かりやすい場合が多い
Style/RedundantSelf:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/models/article_spec.rb'
    - 'spec/models/relationship_spec.rb'
    - 'spec/requests/articles_spec.rb'
    - 'spec/requests/relationships_spec.rb'
    - 'spec/requests/users/registrations_spec.rb'
    - 'spec/system/articles_spec.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/users/confirmations_controller.rb'
    - 'app/controllers/users/omniauth_callbacks_controller.rb'
    - 'app/controllers/users/passwords_controller.rb'
    - 'app/controllers/users/registrations_controller.rb'
    - 'app/controllers/users/sessions_controller.rb'
    - 'app/controllers/users/unlocks_controller.rb'
    - 'test/channels/application_cable/connection_test.rb'
    - 'test/test_helper.rb'

# 変数の比較と代入は、条件式の戻り値を使う
Style/ConditionalAssignment:
  Exclude:
    - 'app/controllers/searchs_controller.rb'

# 条件分岐のネストを深くすしないための技法
Style/GuardClause:
  Exclude:
    - 'app/controllers/article_likes_controller.rb'
    - 'app/controllers/static_pages_controller.rb'

Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'

Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'
##################### Lint ##################################

##################### Metrics ##################################

# 変数の代入(A)、メソッドの呼び出し等(B)、条件分岐(C)から算出される複雑度
Metrics/AbcSize:
  Max: 30

# 循環的複雑度 ≒ 分岐の数
Metrics/CyclomaticComplexity:
  Max: 10

# 1行の文字数
Metrics/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"

# メソッドの行数
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"

Metrics/BlockLength:
  Max: 100
##################### Layout ##################################
Layout/ArgumentAlignment:
  Exclude:
    - 'db/seeds.rb'
    - 'spec/models/relationship_spec.rb'

Layout/BlockEndNewline:
  Exclude:
    - 'spec/models/relationship_spec.rb'
    - 'spec/requests/users/registrations_spec.rb'

Layout/HashAlignment:
  Exclude:
    - 'app/models/article.rb'
    - 'app/models/user.rb'
    - 'db/seeds.rb'
    - 'spec/models/relationship_spec.rb'
    - 'spec/requests/users/registrations_spec.rb'
    - 'spec/requests/users_spec.rb'

Layout/IndentationConsistency:
  Exclude:
    - 'app/controllers/articles_controller.rb'
    - 'db/migrate/20230130151225_create_active_storage_tables.active_storage.rb'

Layout/IndentationWidth:
  Exclude:
    - 'app/controllers/articles_controller.rb'
    - 'db/migrate/20230130151225_create_active_storage_tables.active_storage.rb'
    - 'spec/requests/relationships_spec.rb'

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/models/relationship_spec.rb'
    - 'spec/requests/users/registrations_spec.rb'

Layout/MultilineMethodCallIndentation:
  Exclude:
    - 'app/models/user.rb'

##################### Naming ##################################
Naming/RescuedExceptionsVariableName:
  Exclude:
    - 'app/controllers/turbo_devise_controller.rb'

##################### Rails ##################################
# migarationでadd_indexをすると指摘される
Rails/BulkChangeTable:
  Exclude:
    - 'db/migrate/20230123010632_devise_create_users.rb'
    - 'db/migrate/20230130154909_create_relationships.rb'

Rails/FilePath:
  Exclude:
    - 'spec/rails_helper.rb'

Rails/InverseOf:
  Exclude:
    - 'app/models/user.rb'